source 'https://rubygems.org'

gem 'actionview'
gem 'activesupport'
gem 'dedent'
gem 'dotenv'
gem 'faraday'
gem 'faraday_middleware'
gem 'money'
gem 'newrelic_rpm'
gem 'pg'
gem 'rack-ssl'
gem 'sequel'
gem 'sinatra'
gem 'unicorn'
